# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yy2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QPushButton,  QPlainTextEdit,QMessageBox
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QFileDialog
from PyQt5 import QtWidgets,QtGui,QtCore
import cv2
from PyQt5.QtWidgets import QApplication, QWidget, QLabel, QTextEdit, QTextBrowser, QHBoxLayout, QVBoxLayout


class Ui_Form():
    def setupUi(self, Form):
        Form.setObjectName("仪表检测")
        Form.resize(1243, 933)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0,1243, 933))
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")

        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.label = QtWidgets.QLabel(self.tab1)
        self.label.setGeometry(QtCore.QRect(80, 100, 500, 620))
        self.label.setObjectName("label")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        # self.label_2 = QtWidgets.QLabel(self.tab1)
        # self.label_2.setGeometry(QtCore.QRect(400, 420, 251, 23))
        # self.label_2.setObjectName("label_2")
        # self.graphicsView = QtWidgets.QGraphicsView(self.tab1)
        # self.graphicsView.setGeometry(QtCore.QRect(40, 60, 256, 351))
        # self.graphicsView.setFrameShape(QtWidgets.QFrame.Box)
        # self.pushButtoncamer.setText("")
        # self.graphicsView.setObjectName("pushButtoncamer")
        self.show_text = QtWidgets.QTextBrowser(self.tab1)
        self.show_text.setGeometry(QtCore.QRect(700, 100, 500, 350))
        # self.pushButtonexit.setFrameShape(QtWidgets.QFrame.Box)
        # self.pushButtonexit.setText("")
        # self.graphicsView_2.setObjectName("pushButtonexit")
        self.pushButton = QtWidgets.QPushButton(self.tab1)
        self.pushButton.setGeometry(QtCore.QRect(110, 30, 200, 46))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_result = QtWidgets.QPushButton(self.tab1)
        self.pushButton_result.setGeometry(QtCore.QRect(630, 30, 200, 46))
        self.pushButton_result.setObjectName("pushButton_2")
        self.tabWidget.addTab(self.tab1, "")

        self.tab4 = QtWidgets.QWidget()
        self.tab4.setObjectName("tab4")
        self.label_4 = QtWidgets.QLabel(self.tab4)
        self.label_4.setGeometry(QtCore.QRect(80, 100, 500, 620))
        self.label_4.setObjectName("label")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        # self.label_2 = QtWidgets.QLabel(self.tab1)
        # self.label_2.setGeometry(QtCore.QRect(400, 420, 251, 23))
        # self.label_2.setObjectName("label_2")
        # self.graphicsView = QtWidgets.QGraphicsView(self.tab1)
        # self.graphicsView.setGeometry(QtCore.QRect(40, 60, 256, 351))
        # self.graphicsView.setFrameShape(QtWidgets.QFrame.Box)
        # self.pushButtoncamer.setText("")
        # self.graphicsView.setObjectName("pushButtoncamer")
        self.show_text_4 = QtWidgets.QTextBrowser(self.tab4)
        self.show_text_4.setGeometry(QtCore.QRect(700, 100, 500, 350))
        # self.pushButtonexit.setFrameShape(QtWidgets.QFrame.Box)
        # self.pushButtonexit.setText("")
        # self.graphicsView_2.setObjectName("pushButtonexit")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab4)
        self.pushButton_4.setGeometry(QtCore.QRect(110, 30, 200, 46))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_result_4 = QtWidgets.QPushButton(self.tab4)
        self.pushButton_result_4.setGeometry(QtCore.QRect(630, 30, 200, 46))
        self.pushButton_result_4.setObjectName("pushButton_result_4")
        self.tabWidget.addTab(self.tab4, "")

        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.label_2 = QtWidgets.QLabel(self.tab2)
        self.label_2.setGeometry(QtCore.QRect(50, 70, 200, 200))
        self.label_2.setObjectName("label_2")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.edit_label = QtWidgets.QLabel('QTextEdit',self.tab2)
        self.edit_label.setGeometry(QtCore.QRect(50, 20, 90, 80))
        self.browser_label = QtWidgets.QLabel('QTextBrowser', self.tab2)
        self.browser_label.setGeometry(QtCore.QRect(340, 20, 90, 80))
        self.text_edit = QTextEdit(self.tab2)
        self.text_edit.setGeometry(QtCore.QRect(50, 70, 256, 351))
        self.text_browser = QTextBrowser(self.tab2)
        self.text_browser.setGeometry(QtCore.QRect(340, 70, 256, 351))
        self.tabWidget.addTab(self.tab2, "")

        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.label_showdata = QtWidgets.QLabel(self.tab3)
        self.label_showdata.setGeometry(QtCore.QRect(10, 10, 600, 350))
        # self.label_showdata.setFrameShape(QtWidgets.QFrame.Box)
        # self.label_showdata.setText("")
        # self.label_showdata.setObjectName("label_showdata")
        # self.pushButtonshow = QtWidgets.QPushButton(self.tab3)
        # self.pushButtonshow.setGeometry(QtCore.QRect(170, 200, 111, 41))
        # self.pushButtonshow.setObjectName("pushButtonshow")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab3)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 400, 111, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.graphicsView = QtWidgets.QGraphicsView(self.tab3)
        self.graphicsView.setGeometry(QtCore.QRect(40, 60, 256, 330))
        self.graphicsView.setObjectName("pushButtoncamer")
        # self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.tab3)
        # self.plainTextEdit_2.setGeometry(QtCore.QRect(330,50,230,330))
        # self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.tab3)
        self.graphicsView_2.setGeometry(QtCore.QRect(340, 60, 256, 330))
        self.graphicsView_2.setObjectName("pushButtonexit")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab3)
        self.pushButton_3.setGeometry(QtCore.QRect(320, 400, 111, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tabWidget.addTab(self.tab3, "")
        # self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.tab3)
        # self.plainTextEdit_3.setGeometry(QtCore.QRect(50,50,230,330))
        # self.plainTextEdit_3.setObjectName("plainTextEdit_3")



        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1),"AI标识左右手")
        self.pushButton.setText("打开摄像头")
        self.pushButton_result.setText("关闭摄像头")

        self.pushButton_4.setText("打开摄像头")
        self.pushButton_result_4.setText("关闭摄像头")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), "打字同步")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3),"AI识物")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab4), "AI人脸追踪")
        # self.pushButtonshow.setText("查看")
        self.pushButton_2.setText("选择图片")
        self.pushButton_3.setText("识别结果")
        self.tabWidget.setCurrentIndex(0) #设置初始界面的位置


